unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# C-a is way more ergonomic than the default C-b
set -g prefix C-a

# So C-a C-a is a good way to alternate between two windows
# bind-key C-a last-window # DEPRECATED in favor or tmux-sensible

# At the top the UI is not so polluted when using vim
set-option -g status-position top

# Colours are good
set -g default-terminal "tmux-256color"

# Uncomment if you want to select and resize using mouse
set -g mouse on

# https://www.baeldung.com/linux/tmux-copy-paste-keyboard-mouse#5-customization
setw -g mode-keys vi
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xsel --clipboard --input"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xsel --clipboard --input"
# rectangular selection: https://superuser.com/a/693990
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # rectangular selection

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Confirmation dialogs are annoying
# bind-key & kill-window
bind-key & confirm-before -p "Kill this window #P? (y/n)" kill-window
bind-key x kill-pane

# Bind <prefix> | to split the window vertically
# and <prefix> - to split it horizontally
unbind '"'
unbind %
bind-key | split-window -h
bind-key - split-window -v

# <prefix> C-s to synchronize panes
# bind-key -n C-s set-window-option synchronize-panes\; display-message "Sync #{?pane_synchronized,on,off}"
unbind C-s
# bind-key C-s if-shell 'test #{pane_synchronized}' \
  'set-window-option synchronize-panes off' \
  'set-window-option synchronize-panes on \; display-message "Sync on"'
bind -n C-s set-window-option synchronize-panes

# bind C-s set-window-option synchronize-panes
# TODO: sync with just some panes

# Ease to resize panes
set -g repeat-time 500

# unbind-key -T vi-copy v  # Prior to version 2.4
unbind-key -T copy-mode-vi v

# -------------------------------------------------------------------------------------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# catppuccin {{{
# set -g @catppuccin_flavor "mocha"
# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux # default values
# }}}
# tokyo-night {{{
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_window_id_style none
set -g @tokyo-night-tmux_path_format relative # 'relative' or 'full'
# }}}

# tmux-pain-control {{{
set -g @plugin 'mfandrade/tmux-pain-control'
# }}}

# -------------------------------------------------------------------------------------------------
if "test ! -d ~/.config/tmux/plugins/tpm" \
  "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm \
  && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
run -b '~/.config/tmux/plugins/tpm/tpm' # this must be the last line
