#[theme]
#theme = "semi-native"

[icons]
icons = "material-nf"

[[block]]
block = "rofication"
interval = 30
socket_path = "/tmp/rofi_notification_daemon"
[[block.click]]
button = "left"
cmd = "ilia -p notifications"

[[block]]
block = "time"
interval = 1
format = "$timestamp.datetime(f:'%a,%d/%b') - $timestamp.datetime(f:'%T') $icon"
